### ISSUE TITLE
Magento 2.2.2 - Tablerates not working on Cart Page

### ISSUE THREAD

**Issue by Vikram0811** [flancer32/mage2_fix_is12655#1]
Will the fix can work for this issue - https://github.com/magento/magento2/issues/14171 ? Also can I manually install your extension without composer?

Or

Should I go with this - https://github.com/magento/magento2/commit/aa535e ?

**Comment by flancer64** [comment]
Yes, it can work. This module does the same as https://github.com/magento/magento2/commit/aa535e does - unsets $data['extension_attributes'] with wrong type. I suppose you should apply https://github.com/magento/magento2/commit/aa535e fix manually if you do not use composer in your project. But if you plan to upgrade your project in the future, use this module - it will not be overridden on Magento files upgrades.

**Comment by Vikram0811** [comment]
The point I am making is - I want to use a standalone plugin in order to keep customization separate from core Magento files. I tried your plugin by changing its name and installed manually and I guess it works except for below scenario

User having two address with different zip codes. When I change user's default shipping address to different zip code, it still shows old shipping price. Only when I change zip code in `Shipping and tax estimator` it then shows correct price.

Expected behavior - Whenever user's zip code is changed from account dashboard, the relevant shipping price based on tablerates should reflect on cart page instead of entering that zip code in estimator.

Thanks.

**Comment by flancer64** [comment]
Magento has [a lot of bugs](https://github.com/magento/magento2/issues), my plugin fix only one of them. Described behavior is out of scope of my fix. Sorry.
